"""Reporters: render a RunResult into the formats CI needs.

- markdown      : PR/MR comment + job summary (human readable)
- json          : full machine-readable result
- sarif         : GitHub code scanning (Security tab + inline annotations)
- gitlab        : GitLab Code Quality report (codeclimate JSON subset)
- terminal      : compact console output
"""
from __future__ import annotations

import hashlib
import json
from typing import Dict, List

from .findings import Finding, severity_rank
from .html_report import to_html  # noqa: F401  (re-exported as a reporter format)
from .pipeline import AnalysisResult, RunResult

_GATE_EMOJI = {"pass": "✅", "warn": "⚠️", "block": "⛔"}
_SEV_EMOJI = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "⚪"}


def _fmt_tokens(n: float) -> str:
    """Compact token count, e.g. 12.3M, 450K, 800."""
    n = float(n or 0)
    if n >= 1e9:
        return f"{n / 1e9:.1f}B"
    if n >= 1e6:
        return f"{n / 1e6:.1f}M"
    if n >= 1e3:
        return f"{n / 1e3:.0f}K"
    return f"{n:.0f}"


# --- JSON ----------------------------------------------------------------------
def to_json(run: RunResult, indent: int = 2) -> str:
    return json.dumps(run.to_dict(), indent=indent)


# --- Markdown (PR/MR comment + job summary) ------------------------------------
def to_markdown(run: RunResult) -> str:
    lines: List[str] = []
    gate = run.gate_decision
    lines.append(f"## {_GATE_EMOJI.get(gate, '')} Tollgate — deployment risk: **{gate.upper()}** "
                 f"(max score {run.max_score}/100)")
    lines.append("")
    if not run.results and not run.lint_results and not run.detected_prompts:
        lines.append("_No agent workflows or prompt templates detected in the analyzed paths._")
        return "\n".join(lines)
    if not run.results:
        if run.lint_results:
            lines.append("_No fully-recoverable workflow graph; strict agentic-lint findings below._")
            lines += _lint_section(run)
        lines += _prompt_efficiency_section(run)
        lines += _detected_prompts_section(run)
        return "\n".join(lines)

    # Summary table.
    lines.append("| Workflow | Score | Gate | Proj. tokens/mo (p50→p95) | Top risk |")
    lines.append("|---|---|---|---|---|")
    for r in sorted(run.results, key=lambda x: x.risk.score, reverse=True):
        m = r.risk.projected_monthly_tokens
        top = r.findings[0].category if r.findings else "—"
        lines.append(
            f"| `{r.workflow_id}` | {r.risk.score} | {_GATE_EMOJI.get(r.risk.gate_decision,'')} "
            f"{r.risk.gate_decision} | {_fmt_tokens(m.get('p50',0))} → {_fmt_tokens(m.get('p95',0))} | {top} |"
        )
    lines.append("")

    for r in sorted(run.results, key=lambda x: x.risk.score, reverse=True):
        lines += _workflow_section(r)

    lines += _prompt_efficiency_section(run)
    lines += _lint_section(run)
    lines += _detected_prompts_section(run)

    lines.append("")
    lines.append("<sub>Token projections come from the prediction engine over the configured "
                 "traffic scenarios. Generated by Tollgate.</sub>")
    if run.fingerprint:
        lines.append(f"<sub>Fingerprint <code>{run.fingerprint[:16]}…</code> — "
                     f"re-derivable with <code>tollgate verify</code>.</sub>")
    return "\n".join(lines)


def _detected_prompts_section(run: RunResult) -> List[str]:
    """Embedded prompts mined from source/config (any language). Heuristic +
    advisory — these are *candidates* for the prompt-efficiency review, not gate
    findings."""
    dp = getattr(run, "detected_prompts", None) or []
    if not dp:
        return []
    total = sum(p.est_tokens for p in dp)
    out = ["", f"### Detected prompts in code/config ({len(dp)}, ~{_fmt_tokens(total)} tokens)",
           "_Heuristically detected — string literals that look like LLM prompts. "
           "Review for bloat/injection; not part of the risk gate._", ""]
    out.append("| Location | Name | ~tokens | Why flagged |")
    out.append("|---|---|---|---|")
    for p in dp[:50]:
        loc = (p.source_path.split('/')[-1] if p.source_path else '?') + (f":{p.line}" if p.line else "")
        why = _md_cell(", ".join(p.reasons[:3]), 80)
        out.append(f"| `{loc}` | `{p.name or '—'}` | {p.est_tokens:,} | {why} |")
    if len(dp) > 50:
        out.append(f"| … | … | … | (+{len(dp)-50} more) |")
    out.append("")
    return out


def _lint_section(run: RunResult) -> List[str]:
    """Render strict agentic-lint findings for files with no recoverable graph.
    These are structural-only (no cost projection is invented)."""
    if not run.lint_results:
        return []
    out: List[str] = ["", "### Strict agentic-lint (no recoverable graph)",
                      "_Structural checks only — no token/cost projection for these files._", ""]
    for lr in sorted(run.lint_results, key=lambda x: x.score, reverse=True):
        name = lr.source_path.split("/")[-1] if lr.source_path else "?"
        out.append(f"**`{name}`** — {_GATE_EMOJI.get(lr.gate_decision,'')} "
                   f"{lr.gate_decision} (score {lr.score})")
        for f in sorted(lr.findings, key=lambda x: severity_rank(x.severity), reverse=True):
            loc = f":{f.line}" if f.line else ""
            out.append(f"- `{f.severity}` **{f.category}**{loc} — {_md_cell(f.message)}")
        out.append("")
    return out


def _md_cell(text: str, limit: int = 220) -> str:
    """Make arbitrary prompt text safe and compact for a Markdown table cell."""
    one_line = " ".join((text or "").split())
    if len(one_line) > limit:
        one_line = one_line[: limit - 1].rstrip() + "…"
    # Escape characters that would break a Markdown table / formatting.
    return one_line.replace("\\", "\\\\").replace("|", "\\|").replace("`", "​`")


def _collect_prompt_reviews(run: RunResult):
    """Flatten (workflow_id, review) pairs, biggest token savings first."""
    pairs = []
    for r in run.results:
        for pr in getattr(r, "prompt_reviews", []) or []:
            pairs.append((r.workflow_id, pr))
    # Mined code/config prompts that the reviewer found inefficiencies in.
    for dp in getattr(run, "detected_prompts", None) or []:
        if getattr(dp, "review", None) is not None:
            label = dp.name or (dp.source_path.split("/")[-1] if dp.source_path else "prompt")
            pairs.append((label, dp.review))
    pairs.sort(key=lambda p: p[1].tokens_saved, reverse=True)
    return pairs


def _prompt_efficiency_section(run: RunResult) -> List[str]:
    pairs = _collect_prompt_reviews(run)
    out: List[str] = []
    if not pairs:
        return out
    total_saved = sum(pr.tokens_saved for _, pr in pairs)
    out.append("")
    out.append(f"## ✍️ Prompt token optimisation ({len(pairs)} prompt"
               f"{'s' if len(pairs) != 1 else ''}, "
               f"~{_fmt_tokens(total_saved)} tokens/call reclaimable)")
    out.append("")
    out.append("| Prompt | Current prompt | Recommendation | Example (efficient rewrite) | Saved |")
    out.append("|---|---|---|---|---|")
    for wf_id, pr in pairs:
        node = f"`{wf_id}`/`{pr.node_id}`"
        saved = (f"{pr.tokens_saved} tok ({pr.savings_pct:.0f}%)"
                 if pr.tokens_saved else "structural")
        out.append(
            f"| {node} | {_md_cell(pr.original)} | {_md_cell(pr.recommendation, 320)} "
            f"| {_md_cell(pr.rewritten)} | {saved} |"
        )
    out.append("")
    out.append("<sub>Prompt rewrites are produced by deterministic static rules "
               "(no model call); review before adopting. Token counts are per call.</sub>")
    return out


def _workflow_section(r: AnalysisResult) -> List[str]:
    out: List[str] = []
    out.append(f"### `{r.workflow_id}` — {r.risk.score}/100 "
               f"({_GATE_EMOJI.get(r.risk.gate_decision,'')} {r.risk.gate_decision})")
    if r.risk.reasons:
        for reason in r.risk.reasons:
            out.append(f"- {reason}")
    if r.risk.drivers:
        drv = ", ".join(f"{d['category']} (+{d['contribution']})" for d in r.risk.drivers[:4])
        out.append(f"- **Risk drivers:** {drv}")
    m = r.risk.projected_monthly_tokens
    out.append(f"- **Projected tokens:** ~{_fmt_tokens(m.get('p50',0))}/mo (p50), "
               f"~{_fmt_tokens(m.get('p95',0))}/mo (p95)")
    out.append("")

    # Where the tokens go: per-node share of projected consumption.
    if r.forecast.drivers:
        out.append("**Where the tokens go**")
        out.append("")
        for d in r.forecast.drivers[:5]:
            out.append(f"- `{d.name}`: ~{_fmt_tokens(d.monthly_tokens)}/mo "
                       f"({d.share * 100:.0f}% of request tokens)")
        out.append("")

    if r.findings:
        out.append("**Findings**")
        out.append("")
        for f in sorted(r.findings, key=lambda x: severity_rank(x.severity), reverse=True):
            loc = f" (`{f.node_id}`)" if f.node_id else ""
            out.append(f"- {_SEV_EMOJI.get(f.severity,'')} **{f.severity.upper()}** "
                       f"[{f.category}]{loc}: {f.message}")
        out.append("")

    if r.recommendations:
        out.append("**Model right-sizing** (cost lever — same token volume on a cheaper model)")
        out.append("")
        for rec in r.recommendations:
            out.append(f"- `{rec.node_id}`: {rec.from_model} → **{rec.to_model}** "
                       f"({rec.savings_pct:.0f}% cheaper/call, capability {rec.capability_score:.2f})")
        out.append("")

    if r.remediation.items:
        out.append("**Remediation plan** (token reducers first)")
        out.append("")
        for it in r.remediation.items[:8]:
            sv = it.est_monthly_tokens_saved
            tag = f" — ~{_fmt_tokens(sv)} tokens/mo saved" if sv else ""
            out.append(f"- [{it.effort} effort] {it.title}{tag}")
            if it.suggested_change:
                out.append(f"  ```yaml\n  {it.suggested_change}\n  ```")
        out.append("")
    return out


# --- Terminal ------------------------------------------------------------------
def to_terminal(run: RunResult) -> str:
    lines = []
    lines.append(f"Tollgate — gate: {run.gate_decision.upper()} (max score {run.max_score}/100)")
    if run.fingerprint:
        lines.append(f"  fingerprint: {run.fingerprint[:16]}…  (verify: tollgate verify)")
    for r in sorted(run.results, key=lambda x: x.risk.score, reverse=True):
        m = r.risk.projected_monthly_tokens
        lines.append(f"  [{r.risk.score:>3}] {r.risk.gate_decision:<5} {r.workflow_id}  "
                     f"~{_fmt_tokens(m.get('p50',0))}-{_fmt_tokens(m.get('p95',0))} tok/mo")
        for f in sorted(r.findings, key=lambda x: severity_rank(x.severity), reverse=True):
            node = f"@{f.node_id}" if f.node_id else ""
            lines.append(f"        {f.severity.upper():<8} {f.category} {node}: {f.message}")

    for lr in sorted(run.lint_results, key=lambda x: x.score, reverse=True):
        name = lr.source_path.split("/")[-1] if lr.source_path else "?"
        lines.append(f"  [{lr.score:>3}] {lr.gate_decision:<5} {name}  (agentic-lint, no graph)")
        for f in sorted(lr.findings, key=lambda x: severity_rank(x.severity), reverse=True):
            loc = f":{f.line}" if f.line else ""
            lines.append(f"        {f.severity.upper():<8} {f.category}{loc}: {f.message}")

    dp = getattr(run, "detected_prompts", None) or []
    if dp:
        total = sum(p.est_tokens for p in dp)
        lines.append("")
        lines.append(f"Detected prompts in code/config — {len(dp)} (~{_fmt_tokens(total)} tokens, "
                     f"heuristic, advisory):")
        for p in dp[:20]:
            loc = (p.source_path.split('/')[-1] if p.source_path else '?') + (f":{p.line}" if p.line else "")
            lines.append(f"  {loc}  [{p.name or '—'}]  ~{p.est_tokens} tok  ({', '.join(p.reasons[:2])})")
        if len(dp) > 20:
            lines.append(f"  (+{len(dp)-20} more)")

    pairs = _collect_prompt_reviews(run)
    if pairs:
        total_saved = sum(pr.tokens_saved for _, pr in pairs)
        lines.append("")
        lines.append(f"Prompt token optimisation — {len(pairs)} prompt(s), "
                     f"~{_fmt_tokens(total_saved)} tokens/call reclaimable:")
        for wf_id, pr in pairs:
            saved = (f"-{pr.tokens_saved} tok ({pr.savings_pct:.0f}%)"
                     if pr.tokens_saved else "structural")
            lines.append(f"  {wf_id}/{pr.node_id}  [{saved}]")
            lines.append(f"      before: {_term_snip(pr.original)}")
            lines.append(f"      after : {_term_snip(pr.rewritten)}")
            lines.append(f"      fix   : {_term_snip(pr.recommendation, 160)}")
    return "\n".join(lines)


def _term_snip(text: str, limit: int = 120) -> str:
    one_line = " ".join((text or "").split())
    return one_line if len(one_line) <= limit else one_line[: limit - 1] + "…"


# --- SARIF (GitHub code scanning) ----------------------------------------------
_SARIF_LEVEL = {"critical": "error", "high": "error", "medium": "warning", "low": "note"}


def to_sarif(run: RunResult) -> str:
    rules = {}
    results = []
    for r in run.results:
        for f in r.findings + r.policy_violations:
            rule_id = f"tollgate/{f.category}"
            rules.setdefault(rule_id, {
                "id": rule_id,
                "name": f.category,
                "shortDescription": {"text": f.category.replace("_", " ").title()},
                "defaultConfiguration": {"level": _SARIF_LEVEL.get(f.severity, "warning")},
            })
            location = {
                "physicalLocation": {
                    "artifactLocation": {"uri": _rel(f.source_path or r.source_path or "workflow")},
                    "region": {"startLine": f.line or 1},
                }
            }
            results.append({
                "ruleId": rule_id,
                "level": _SARIF_LEVEL.get(f.severity, "warning"),
                "message": {"text": f.message},
                "locations": [location],
                "partialFingerprints": {
                    "primary": hashlib.sha1(
                        f"{r.workflow_id}:{f.finding_id}:{f.message}".encode()).hexdigest()
                },
            })
    for lr in run.lint_results:
        for f in lr.findings:
            rule_id = f"tollgate/{f.category}"
            rules.setdefault(rule_id, {
                "id": rule_id,
                "name": f.category,
                "shortDescription": {"text": f.category.replace("_", " ").title()},
                "defaultConfiguration": {"level": _SARIF_LEVEL.get(f.severity, "warning")},
            })
            results.append({
                "ruleId": rule_id,
                "level": _SARIF_LEVEL.get(f.severity, "warning"),
                "message": {"text": f.message},
                "locations": [{"physicalLocation": {
                    "artifactLocation": {"uri": _rel(f.source_path or lr.source_path or "agent")},
                    "region": {"startLine": f.line or 1}}}],
                "partialFingerprints": {
                    "primary": hashlib.sha1(
                        f"{lr.source_path}:{f.finding_id}:{f.message}".encode()).hexdigest()
                },
            })
    doc = {
        "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
        "version": "2.1.0",
        "runs": [{
            "tool": {"driver": {
                "name": "Tollgate",
                "informationUri": "https://github.com/tollgate/tollgate",
                "rules": list(rules.values()),
            }},
            "results": results,
        }],
    }
    return json.dumps(doc, indent=2)


# --- GitLab Code Quality (codeclimate subset) ----------------------------------
_GITLAB_SEV = {"critical": "blocker", "high": "critical", "medium": "major", "low": "minor"}


def to_gitlab_codequality(run: RunResult) -> str:
    out = []
    for r in run.results:
        for f in r.findings + r.policy_violations:
            path = _rel(f.source_path or r.source_path or "workflow")
            fp = hashlib.sha1(f"{r.workflow_id}:{f.finding_id}:{f.message}".encode()).hexdigest()
            out.append({
                "description": f"[{f.category}] {f.message}",
                "check_name": f"tollgate/{f.category}",
                "fingerprint": fp,
                "severity": _GITLAB_SEV.get(f.severity, "major"),
                "location": {"path": path, "lines": {"begin": f.line or 1}},
            })
    for lr in run.lint_results:
        for f in lr.findings:
            path = _rel(f.source_path or lr.source_path or "agent")
            fp = hashlib.sha1(f"{lr.source_path}:{f.finding_id}:{f.message}".encode()).hexdigest()
            out.append({
                "description": f"[{f.category}] {f.message}",
                "check_name": f"tollgate/{f.category}",
                "fingerprint": fp,
                "severity": _GITLAB_SEV.get(f.severity, "major"),
                "location": {"path": path, "lines": {"begin": f.line or 1}},
            })
    return json.dumps(out, indent=2)


def _rel(path: str) -> str:
    import os
    try:
        return os.path.relpath(path)
    except Exception:
        return path
